### ISSUE TITLE
vsim backend code quality/rewrite

### ISSUE THREAD

**Issue by jvanstraten** [abs-tudelft/vhdeps#23]
The quality of the vsim backend is pretty abysmal compared to the rest of vhdeps, since it's basically just the handwritten TCL script that was used within Fletcher in a multiline string with some barely-structured lists being generated by vhdeps at the end, with hardcoded indices to boot. It basically requires a rewrite before #13, #16, and #18 can be implemented.

**Comment by jvanstraten** [comment]
Requirements:

 - [ ] TCL script must support batch mode and interactive GUI mode, i.e. there should be a single script for both.
 - [ ] Test cases should be run from the working directory they're defined in (new feature, #16).
 - [ ] There should be a way to specify custom vsim flags on a per-test-case basis (new feature).

Batch mode functions:

 - [ ] The TCL script should produce a file with the test case results in some standardized format (new feature, #13).
 - [ ] A summary of the test results should be printed when the script completes, similar to the GHDL backend (preferably identical to it).

Interactive mode functions:

 - [ ] When the user calls vhdeps with a single test case, this test case should be run automatically at startup and left open. When there is more than one test case, the entire suite should be run similar to batch mode, and the final test case should be closed.
 - [ ] After the initial run of a test suite with multiple test cases, the user must be able to rerun the suite (after automatic incremental recompilation) or run the first failing test case interactively through TCL commands.
 - [ ] After an interactive test case run, the user must be able to recompile/rerun with a TCL command. This command should restore the waveform view and signals.
 - [ ] TCL commands should be generated to run specific test cases (new feature).
 - [ ] When a test case is first run, the TCL script should automatically add relevant waveforms. This should not be hardcoded as it was before (updated, #18).

Maybe:

 - [ ] Coverage?

**Comment by jvanstraten** [comment]
Still need some regression tests to reach 100% coverage, but all features are there.
